# Generated by Django 4.0.6 on 2022-07-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='User Name')),
                ('email', models.EmailField(db_index=True, max_length=200, verbose_name='Email')),
                ('password', models.CharField(db_index=True, max_length=255, verbose_name='Password')),
                ('token', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
