# Generated by Django 4.0.6 on 2022-07-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(db_index=True, verbose_name='Total Price')),
                ('customer_name', models.CharField(db_index=True, max_length=255, verbose_name='Customer Name')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Address')),
                ('building_type', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Building Type')),
                ('city', models.CharField(db_index=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(db_index=True, max_length=255, verbose_name='State')),
                ('pin_code', models.CharField(db_index=True, max_length=255, verbose_name='Pin Code')),
                ('total_qty', models.IntegerField(db_index=True, max_length=11, verbose_name='Total Qty')),
                ('customer_phone', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Customer Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_index=True, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
